CLASS zcl_12_travellog DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC FOR EVENTS OF z12_r_travel.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_12_travellog IMPLEMENTATION.
ENDCLASS.
